### ISSUE TITLE
Syntax error when updating attributes

### ISSUE THREAD

**Issue by rtjc** [Inchoo/Inchoo_PHP7#59] opened 2016-08-02 12:45 UTC
Hi guys,

we have PHP7 up and running in our shop. Now we came across a problem, we cannot edit our attributes. We came across this problem when adding a new brand in our 'manufacturer' attributes. 

We get this error: Decoding failed: Syntax error

What to do?

**Comment by icurdinj** [comment] 2016-08-03 10:15
This could be caused by JSON decoding incompatibility, which is fixed by Inchoo_PHP7... Please check if the extension is properly installed, caches cleared, etc...
If you are still having problems, a more detailed error report (PHP stack trace, for example) would be of help.

**Comment by rtjc** [comment] 2016-08-03 18:23
Hi,

there is no stack trace generated so far. We have found out as soon as we disable the Gomage Advanced Navigation module, the problems disappear.

**Comment by icurdinj** [comment] 2016-08-04 06:38
Ok. Well, then it's another case of 3rd party extension not being compatible with PHP7. We get that all the time :-)

**Closed by icurdinj** 2016-08-04 06:38 UTC
