### ISSUE TITLE
Magento 1.9.2.4 and php 7.0.6

### ISSUE THREAD

**Issue by tomekjordan** [Inchoo/Inchoo_PHP7#48] opened 2016-06-09 11:36 UTC
Hi. despite those fixes, I'm unable to login into admin area with PHP 7.0.6
with php 7.0.0 and 7.0.1 it works.
I use SSL

**Comment by icurdinj** [comment] 2016-06-09 13:40
I've got no problems with 7.0.6. Can you be more specific?

**Comment by tomekjordan** [comment] 2016-06-09 13:54
what you like to know. When I try to login as admin, page is reloaded to the same state showing admin login fields. on php 7.0.01 and 7.0.1 login works

**Comment by ivanweiler** [comment] 2016-06-09 14:01
I have 2 questions:
1. Are session stored in files? (or memcache, redis, etc)
2. Can you login as a customer on frontend?

Thanks

**Comment by tomekjordan** [comment] 2016-06-09 14:23
HI. I tested it deeply and I'm getting also error 500,
1. sessions are store > for users > because admin cannot login > err 500 or reload
2. can login
3. magento is on ubuntu - production > works well VPS for other Magento sites

I see apache logs with:
[Thu Jun 09 16:15:08.267784 2016] [access_compat:error] [pid 8316] [client 185.49.15.167:45394] AH01797: client denied by server configuration: /home/admin/domains/domain.eu/public_html/app/etc/local.xml
[Thu Jun 09 16:15:41.528143 2016] [fcgid:warn] [pid 10789] (104)Connection reset by peer: [client 93.175.69.2:57785] mod_fcgid: error reading data from FastCGI server, referer: http://domain.eu/index.php/admin/cache/index/key/a23537fc6a58eb82b045593bb446bcc5/
[Thu Jun 09 16:15:41.528188 2016] [core:error] [pid 10789] [client 93.175.69.2:57785] End of script output before headers: index.php, referer: http://domain.eu/index.php/admin/cache/index/key/a23537fc6a58eb82b045593bb446bcc5/
[Thu Jun 09 16:15:41.713136 2016] [include:warn] [pid 10789] [client 93.175.69.2:57785] AH01374: mod_include: Options +Includes (or IncludesNoExec) wasn't set, INCLUDES filter removed: /500.shtml, referer: http://domain.eu/index.php/admin/cache/index/key/a23537fc6a58eb82b045593bb446bcc5/
[Thu Jun 09 16:16:17.816564 2016] [fcgid:warn] [pid 10909] (104)Connection reset by peer: [client 93.175.69.2:57798] mod_fcgid: error reading data from FastCGI server
[Thu Jun 09 16:16:17.816597 2016] [core:error] [pid 10909] [client 93.175.69.2:57798] End of script output before headers: index.php

**Comment by igorwulff** [comment] 2016-06-24 06:06
Hi all, is anything more known about this issue? I don't have any problems on my local machine, my staging environment is however having the same issues. If anyone has any pointers or knows a solution, please let me know.

**Comment by icurdinj** [comment] 2016-06-24 12:07
@igorwulff - then you are in great position to give us more details on this. What's different between your local and staging machines?

**Comment by igorwulff** [comment] 2016-06-28 08:11
@icurdinj - main difference I know of is on staging we have to set a flag in the .htaccess to enforce cgi-php70 for using/testing PHP 7. Also the exact PHP variant used, settings, modules, etc... may differ a small bit from my local environment.

**Comment by tomekjordan** [comment] 2016-06-28 08:35
My observations are: Php 7.0.0-1 works well on M1924. PHP 7.0.5,7.0.6.7.07 produce 500. While M1922 with php 7.0.6-7.0.7 almost work - meaning shows admin login page - but I cannot login. I have exact same htaccess for all stores. So I don't know if there could be a problem located....

**Comment by icurdinj** [comment] 2016-06-28 10:11
@igorwulff , @tomekjordan - I'm working right now on a project with M1.9.2.4 and PHP 7.0.6, and can't see any of the problems you are describing. Once again, as @ivanweiler already asked - what session storage do you guys use?

**Comment by tomekjordan** [comment] 2016-06-28 10:14
HI. if you have no problems, it doesn't mean that 99% other Magento instances work on php 7.0.5-707. I have pure M1924, default settings, no tunes, file sessions - like in normal env. As I said - if I only change it to php 7.0.0 or 7.0.1 it works, when I switch to php 7.05-7.07 it triggers error 500 for admin login url. thats all

**Comment by igorwulff** [comment] 2016-06-29 12:35
@icurdinj, session are here saved to the db, but I have the same issue when set to files. No other caching like reddis. I have no issues when logging in as a customer.

**Comment by icurdinj** [comment] 2016-06-29 13:05
@tomekjordan sure, why not. Setup those environments, and we'll see where it crashes. (Just one note - when we find time. As we previously said: this is a developer level extension, no support except community free will.)

**Comment by tomekjordan** [comment] 2016-06-29 15:26
Hi. So here are 2 environments on the same server:

[](http://php701.innovaction.pl/admin)
http://php701.innovaction.pl/phpinfo.php

[](http://php706.innovaction.pl/admin)
http://php706.innovaction.pl/phpinfo.php

Error 500 appears when you try to login to admin area
user: admin pass: test123
FTP: on request in priv msg

**Comment by icurdinj** [comment] 2016-07-04 07:01
@tomekjordan can you send PHP error logs from php706 environment? Or give me access to it?

**Comment by tomekjordan** [comment] 2016-07-04 07:33
[Mon Jul 04 08:56:44.772038 2016] [fcgid:warn] [pid 15905] (104)Connection reset by peer: [client 213.147.103.86:50490] mod_fcgid: error reading data from FastCGI server, referer: http://php706.innovaction.pl/admin
[Mon Jul 04 08:56:44.772064 2016] [core:error] [pid 15905] [client 213.147.103.86:50490] End of script output before headers: index.php, referer: http://php706.innovaction.pl/admin
[Mon Jul 04 08:56:44.841900 2016] [fcgid:warn] [pid 15905] (104)Connection reset by peer: [client 213.147.103.86:50490] mod_fcgid: error reading data from FastCGI server, referer: http://php706.innovaction.pl/admin
[Mon Jul 04 08:56:44.841919 2016] [core:error] [pid 15905] [client 213.147.103.86:50490] End of script output before headers: index.php, referer: http://php706.innovaction.pl/admin
[Mon Jul 04 08:56:44.841966 2016] [include:warn] [pid 15905] [client 213.147.103.86:50490] AH01374: mod_include: Options +Includes (or IncludesNoExec) wasn't set, INCLUDES filter removed: /500.shtml, referer: http://php706.innovaction.pl/admin

**Comment by icurdinj** [comment] 2016-07-04 07:44
That's a web server log. Please post the PHP error log.

**Comment by tomekjordan** [comment] 2016-07-04 07:49
where can I find it? location? or it should be just magento log?

**Comment by icurdinj** [comment] 2016-07-04 08:01
Let me google that for you: http://stackoverflow.com/questions/5127838/where-does-php-store-the-error-log-php5-apache-fastcgi-cpanel

Magentos exception log might catch something also, yes.

**Comment by tomekjordan** [comment] 2016-07-04 08:19
admin login triggers only this in logs
[Mon Jul 04 10:17:45.054522 2016] [fcgid:error] [pid 7147] mod_fcgid: process /fcgi/admin/php706.innovaction.pl.sh(27607) exit(communication error), get unexpected signal 11
[Mon Jul 04 10:17:45.054598 2016] [fcgid:error] [pid 7147] mod_fcgid: process /fcgi/admin/php706.innovaction.pl.sh(25670) exit(communication error), get unexpected signal 11

**Comment by icurdinj** [comment] 2016-07-04 09:33
Ok, let's try something different - can you try how login works with PHP 7.0.8? If it's some regression they introduced in 7.0.5 or 7.0.6, maybe it's fixed by now?

**Comment by tomekjordan** [comment] 2016-07-04 11:12
HI, updated to 7.0.8 no luck. the same err 500

PHP Warning:  Module 'Zend OPcache' already loaded in Unknown on line 0
PHP Warning:  Zend OPcache: module registration failed! in Unknown on line 0
Failed loading /usr/local/ioncube/ioncube_loader_lin_5.6.so:  /usr/local/ioncube/ioncube_loader_lin_5.6.so: undefined symbol: zend_execute_ex
Failed loading opcache.so:  opcache.so: cannot open shared object file: No such file or directory
Failed loading opcache.so:  opcache.so: cannot open shared object file: No such file or directory
Failed loading /usr/local/ioncube/ioncube_loader_lin_5.6.so:  /usr/local/ioncube/ioncube_loader_lin_5.6.so: undefined symbol: zend_execute_ex
Failed loading opcache.so:  opcache.so: cannot open shared object file: No such file or directory
Failed loading opcache.so:  opcache.so: cannot open shared object file: No such file or directory
[Mon Jul 04 13:07:54.730350 2016] [fcgid:error] [pid 11505] mod_fcgid: process /fcgi/admin/php706.innovaction.pl.sh(11714) exit(communication error), get unexpected signal 11
[Mon Jul 04 13:07:54.730440 2016] [fcgid:error] [pid 11505] mod_fcgid: process /fcgi/admin/php706.innovaction.pl.sh(11698) exit(communication error), get unexpected signal 11

**Comment by igorwulff** [comment] 2016-07-04 12:30
Why is it trying to load the ioncube loader? I thought it wasn't supported yet for PHP 7. https://www.ioncube.com/loaders/support_comparison.php

**Comment by tomekjordan** [comment] 2016-07-04 13:22
I don't like to load ion cube, but this log is from whole server, where other domains are on php 5.6 so probably it comes from other domain. I attached more lines - to be sure nothing is missing. but those lines with ion cube are probably not related to php 7.08 and this domain

**Comment by derghostface** [comment] 2016-07-12 17:25
I have the same problem with 1.9.2.4 and PHP 7.0.6. Any news on this issue?

**Comment by akkermanronald** [comment] 2016-07-12 21:39
Same here, 1.9.2.4 on PHP 7.08.

**Comment by tawfekov** [comment] 2016-07-12 22:00
Hello , 

just to clarify , I'm running many magneto store V**1.9.2.4** on **PHP 7.0.8-3+deb.sury.org~xenial+1** & **PHP 7.0.8-2+deb.sury.org~xenial+1 (cli) ( NTS )**  with no issues at all 

I'm using nginx 1.10 + php-fpm 

1. what is your affected OS ? 
2. is it compiled from source or installed from repo , if it was installed form repo what is the repo name / url ? 
3. are you using apache + php-fpm or nginx + fpm or apache + modphp ?  
4. the output of php -m OR list of installed modules would be handy 

I'm writing down my specs so we can  know what is recipe that works and what is not working

**Comment by tomekjordan** [comment] 2016-07-12 22:11
Hi. I gave you access to pure Magento 1924 with php 7.0.1 vs php 7.0.8. apache 2.4 fast-cgi on debian. there is just clean magento installed by Installatron from official repo. no other things intalled except Inchoo php 7 fix.

**Comment by derghostface** [comment] 2016-07-13 06:19
My server setup:
- Apache 2.4.20 with PHP 7.0.6 as CGI (not FastCGI), it's a shared hosting account from df.eu
- php -m output: [php-m.txt](https://github.com/Inchoo/Inchoo_PHP7/files/360818/php-m.txt)
- phpinfo() output: [phpinfo.pdf](https://github.com/Inchoo/Inchoo_PHP7/files/360822/phpinfo.pdf)

**Comment by akkermanronald** [comment] 2016-07-13 07:27
My server setup (used for dev only):

- CentOS7.2.15.11 (core)
- Plesk 12.5.30 update 40.
- PHP 7.08
- Nginx 1.11.1-centos7.16060209
- Magento 1.9.2.4 fresh install, nothing but incl. Inchoo extension
- Running Magento as "PHP application served by nginx"
- phpinfo output:
[phpinfo.pdf](https://github.com/Inchoo/Inchoo_PHP7/files/360906/phpinfo.pdf)

Magento 2.1 working fine on the same server.
Switching Magento 1.9.2.4 back to 5.6 with nginx works fine.

Perhaps the error log can provide some clues:
[error_log.txt](https://github.com/Inchoo/Inchoo_PHP7/files/360913/error_log.txt)

**Comment by tomekjordan** [comment] 2016-07-13 07:48
@akkermanronald your error is generic. its fixed with 1 line. you should fix it before go for php7. you can also install inchoo php7 fix. we talk about more serious problem here - that we cannot access admin area - which gives error 500

**Comment by akkermanronald** [comment] 2016-07-13 08:02
Thx for your prompt reply, sorry this dev instance was not open to public access, but I have changed the firewall settings now. Inchoo module is installed. It's a fresh install, OS and Magento. 

When we switch the same instance back to php 5.6 with nginx all is fine.

**Comment by akkermanronald** [comment] 2016-07-13 21:05
Problem solved by re-installing extension, clearing and refreshing cache! Thx

**Comment by tomekjordan** [comment] 2016-07-13 21:13
@akkermanronald as I wrote, your problem was not related to our problem. we have much bigger issue - we can't login to admin area with php 7.06 and later > err 500

**Comment by derghostface** [comment] 2016-07-14 11:15
Some more infos regarding this issue:
- Backend-Login **does NOT work** with 7.0.6.
- Backend **does work** (when I login with 5.6 and continue to work with 7.0.6).
- Frontend-Login **does work** with 7.0.6.

**Comment by icurdinj** [comment] 2016-07-14 11:33
@derghostface - since I can't reproduce this problem, it would be of help if you could provide PHP stack trace of the crash.

**Comment by derghostface** [comment] 2016-07-14 13:52
@icurdinj I tried, but I don't get any output. Tried it with display_errors = on in php.ini, but it alway shows error 500 and nothing more. Do you have a hint how to get a PHP stack trace?
I attached the excerpt of the apache access log, the apache error log does not show any errors.

![apache-accesslog](https://cloud.githubusercontent.com/assets/991597/16841715/c6511e2c-49da-11e6-9a5a-4a7f39f581fa.png)

**Comment by danslo** [comment] 2016-07-14 14:17
So, 500's are in many cases just swallowed errors. Can you uncomment the lines for setIsDeveloperMode (remove if statements around it) and error_reporting in index.php?

**Comment by derghostface** [comment] 2016-07-14 19:55
@danslo: didn't work, still only the error 500 message.
@icurdinj: I could provide ftp and backend access to a fresh magento installation on this server (in a quota). Is this ok for you?

**Comment by mblarsen** [comment] 2016-07-16 01:10
Some debugging tips: https://github.com/Inchoo/Inchoo_PHP7/issues/40#issuecomment-232940004

**Comment by derghostface** [comment] 2016-07-18 07:20
@mblarsen: this does not help in this case.
@icurdinj: I set up the test system with blank magento 1.9.2.4 and Inchoo_PHP7. If you are interested in helping to debug the error, please contact me via simon.wuerstle@gmail.com and I give you access.

**Comment by derghostface** [comment] 2016-07-21 14:13
So as @icurdinj is not answering: can anybody else help to debug? As I already said: I set up a blank installation for testing and you can destroy everything if needed ;-) I can give you a ssh login and access to the backend as admin user. Please contact me via simon.wuerstle@gmail.com.
As it's on a shared hosting environment you can't have access to the apache config.

**Comment by durzel** [comment] 2016-07-21 14:20
To be fair to @icurdinj I don't think your problem is related to this extension.  I am using it fine with PHP 7.0.7 (php70w-7.0.7-1.w7.x86_64)

**Comment by derghostface** [comment] 2016-07-21 18:13
Pretty sure that this issues is not related to this extension. But this is an extension which has the goal to make magento compatible with PHP 7 and many users have this issue (see comments here or other resources like stackoverflow). So maybe this issue (when the origin of it is found) can be fixed with this extension.

**Comment by spinsch** [comment] 2016-07-22 13:00
@tomekjordan i had the same problem with magento itself without this extension (backend login didn't work). my fault was "wrong owner/group" for all files on my root directory.

```sudo chown -R www-data.www-data /var/www/html/shop.magento.example/```

**Comment by tomekjordan** [comment] 2016-07-22 13:34
@spinsch group/user rights are correct on my vps

**Comment by derghostface** [comment] 2016-07-22 18:56
I finally got the output of the Apache error log when the 500 error happens:
End of script output before headers: index.php

**Comment by tomekjordan** [comment] 2016-07-22 19:43
Whats the option to fix it?

**Comment by icurdinj** [comment] 2016-08-03 10:27
@derghostface "End of script output before headers: index.php", just means that PHP crashed. Get us the PHP error log, so we have some clue what's happening with your setup.

**Comment by derghostface** [comment] 2016-08-22 14:37
Sorry for late response!

I contacted my webhoster and it took a while until they investigated. Today they replied, that there are several reports and patches regarding this problem which where included in a newer php version (newer than 7.0.6.)
They did a test with my installation and PHP 7.0.10 and accordiong to them it worked. Unfortunately they don't officially provide this PHP version yet and so I can't test it myself. Anyone else here having this problem who can test it with 7.0.10?

**Comment by igorwulff** [comment] 2016-08-22 16:11
Thanks for your info. I will try and look this week what version we are currently working with on our staging environments.

**Comment by akkermanronald** [comment] 2016-08-22 16:43
We use PHP 7.09 succesfully with Magento 1.9.2.2 and 1.9.2.4 (with Inchoo extension).

**Comment by tomekjordan** [comment] 2016-08-22 17:09
Confirmed Php 7.0.10 works! and login to admin area is not triggering error 500 anymore! thanks

**Comment by icurdinj** [comment] 2016-08-23 09:41
Nice to see this solved finally :relieved:

**Closed by icurdinj** 2016-08-23 09:41 UTC

**Comment by tomekjordan** [comment] 2016-09-06 15:25
Little update: Php 7.0.10 works well, but produces reports like this:
what about this? its multiplicating all the time.

Thanks for help

a:5:{i:0;s:29:"Decoding failed: Syntax error";i:1;s:2844:"#0 /home/admin/domains/domain.com/public_html/app/code/core/Mage/Core/Helper/Data.php(659): Zend_Json::decode('', 1)
#1 /home/admin/domains/domain.com/public_html/app/code/core/Mage/Persistent/Model/Session.php(133): Mage_Core_Helper_Data->jsonDecode(NULL)
#2 /home/admin/domains/domain.com/public_html/app/code/core/Mage/Core/Model/Abstract.php(226): Mage_Persistent_Model_Session->_afterLoad()
#3 /home/admin/domains/domain.com/public_html/app/code/core/Mage/Persistent/Model/Session.php(154): Mage_Core_Model_Abstract->load('deleted', 'key')
#4 /home/admin/domains/domain.com/public_html/app/code/core/Mage/Persistent/Helper/Session.php(67): Mage_Persistent_Model_Session->loadByCookieKey()
#5 /home/admin/domains/domain.com/public_html/app/code/core/Mage/Persistent/Helper/Session.php(91): Mage_Persistent_Helper_Session->getSession()
#6 /home/admin/domains/domain.com/public_html/app/code/core/Mage/Persistent/Model/Observer.php(177): Mage_Persistent_Helper_Session->isPersistent()
#7 /home/admin/domains/domain.com/public_html/app/code/core/Mage/Core/Model/App.php(1357): Mage_Persistent_Model_Observer->emulateQuote(Object(Varien_Event_Observer))
#8 /home/admin/domains/domain.com/public_html/app/code/core/Mage/Core/Model/App.php(1336): Mage_Core_Model_App->_callObserverMethod(Object(Mage_Persistent_Model_Observer), 'emulateQuote', Object(Varien_Event_Observer))
#9 /home/admin/domains/domain.com/public_html/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('controller_acti...', Array)
#10 /home/admin/domains/domain.com/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(527): Mage::dispatchEvent('controller_acti...', Array)
#11 /home/admin/domains/domain.com/public_html/app/code/core/Mage/Core/Controller/Front/Action.php(69): Mage_Core_Controller_Varien_Action->preDispatch()
#12 /home/admin/domains/domain.com/public_html/app/code/core/Mage/Customer/controllers/AccountController.php(65): Mage_Core_Controller_Front_Action->preDispatch()
#13 /home/admin/domains/domain.com/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(407): Mage_Customer_AccountController->preDispatch()
#14 /home/admin/domains/domain.com/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index')
#15 /home/admin/domains/domain.com/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#16 /home/admin/domains/domain.com/public_html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#17 /home/admin/domains/domain.com/public_html/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#18 /home/admin/domains/domain.com/public_html/index.php(83): Mage::run('', 'store')
#19 {main}";s:3:"url";s:18:"/customer/account/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:7:"default";}

**Comment by versedi** [comment] 2016-09-07 11:32
@tomekjordan you're trying to pass an empty string to json_decode which will end with a syntax error.
You need to validate your data before decoding it. 

As an example try to pass '{}':
`var_dump(Zend_Json::decode('{}', 1));`

Probably related:http://stackoverflow.com/a/36400975

**Comment by tomekjordan** [comment] 2016-09-07 11:50
Hm.. I'm not a dev. which files should I investigate?
